def lg():
    c=Toplevel(dms)
    c.geometry("270x350")
    frame1 = LabelFrame(c, text="Language")
    frame1.pack(fill="both")
    ttk.Label(frame1, text = "Language",font = ("Calibri", 12)).grid(column = 0,row = 0, padx = 10, pady = 70)
    n=StringVar()
    m=ttk.Combobox(frame1,textvariable=n,width=20)
    m['values'] = ("English","Hindi","Telugu","Korean","Chinese","Japanese","Persian","Russian","French")
    m.grid(column = 1, row = 0, padx = 30, pady = 70)
    m.current()
    frame2 = LabelFrame(c, text="Genre")
    frame2.pack(fill="both", expand="yes")
    checkvar1 = IntVar()    
    checkvar2 = IntVar()    
    checkvar3 = IntVar()
    checkvar4 = IntVar()
    checkvar5 = IntVar()
    checkvar6 = IntVar()
    checkvar7 = IntVar()
    Checkbutton(frame2, text = "Pop", variable = checkvar1).place(x=10,y=10)       
    Checkbutton(frame2, text = "Jazz", variable = checkvar2).place(x=10,y=30)
    Checkbutton(frame2, text = "Rock", variable = checkvar3).place(x=10,y=50)
    Checkbutton(frame2, text = "Hip-Hop", variable = checkvar4).place(x=70,y=10)
    Checkbutton(frame2, text = "K-Pop", variable = checkvar5).place(x=70,y=50)
    Checkbutton(frame2, text = "R&B", variable = checkvar6).place(x=35,y=80)
    Checkbutton(frame2, text = "EDM", variable = checkvar7).place(x=70,y=30)
    def display_lg():
        sd=Toplevel(dms)
        sd.title("Songs Display")
        tree = ttk.Treeview(sd)
        tree = ttk.Treeview(sd, columns=("Song_Album_Name","Genre","Language"), show='headings')
        tree.heading("Song_Album_Name", text="Song_Album_Name",anchor=CENTER)
        tree.heading("Genre", text="Genre",anchor=CENTER)
        tree.heading("Language", text="Language",anchor=CENTER)
        tree.pack()       
        def show3():
            check1=checkvar1.get()
            check2=checkvar2.get()
            check3=checkvar3.get()
            check4=checkvar4.get()
            check5=checkvar5.get()
            check6=checkvar6.get()
            check7=checkvar7.get()
            Language=m.get()
            mysqldb = mysql.connector.connect(host="localhost", user="root", password="",database="dmsdb")
            mycursor = mysqldb.cursor()
            q="SELECT * FROM lg WHERE (check1,check2,check3,check4,check5,check6,check7)=(%s,%s,%s,%s,%s,%s,%s);"
            val=(check1,check2,check3,check4,check5,check6,check7,)
            mycursor.execute(q,val)
            records = mycursor.fetchall()
            for i, (Song_Album_Name,Genre,Language) in enumerate(records, start=1):
                tree.insert("", 'end', values=(Song_Album_Name,Genre,Language))
            mysqldb.close()
        show3()
        sd.mainloop()
    Button(c,text="Search",command=display_lg).pack(side=BOTTOM)
    c.mainloop() 